import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {Database} from '../lib/platform/database.ts';
import {createHandlers} from '../lib/atlas/handlers.ts';
import {analytics,EMPTY} from '../lib/atlas/contracts.ts';
import {resolve,join} from 'node:path';
import {readFile,readdir,mkdtemp,rm,writeFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';

const origin='http://atlas.test';
const owner='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const rateUser='cccccccc-cccc-4ccc-8ccc-cccccccccccc',quotaUser='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const companyInput={name:'Harbor Test Studio',industry:'Software',location:'Bangkok',website:'https://example.com',contact_email:'recruiter@example.test',notes:'University internship team'};
const applicationInput=(companyId)=>({company_id:companyId,role:'Product Intern',stage:'Wishlist',location:'Bangkok',work_mode:'Hybrid',job_url:'https://example.com/jobs',applied_on:'',deadline:'2026-12-31',priority:'High',compensation:'Not specified',next_step:'Prepare portfolio'});
const interviewInput=(applicationId)=>({application_id:applicationId,title:'Case interview',starts_at:'2026-11-12T14:00:00+07:00',duration_minutes:45,format:'Video call',location:'Online',meeting_url:'https://example.com/meeting',interviewer:'Hiring team',status:'Scheduled',notes:'Prepare one project example'});
const editable=(record,keys)=>Object.fromEntries(keys.map(k=>[k,record[k]]));
const aKeys=Object.keys(applicationInput(''));
const iKeys=Object.keys(interviewInput(''));
const dKeys=['application_id','name','kind','status','notes'];
let count=0;
await test('Atlas PostgreSQL integration — major workflows',async t=>{
 const state=await mkdtemp(join(tmpdir(),'atlas-integration-'));
 let pg=new PGlite(join(state,'postgres'));
 // Supabase's managed Storage schema is verified through its SDK and remote checks.
 for (const migration of (await readdir('supabase/migrations')).filter(name=>name.endsWith('.sql') && name!=='202609090002_storage.sql').sort()) {
  await pg.exec(await readFile(join('supabase/migrations',migration),'utf8'));
 }
 function repository() { return new Database(work=>pg.transaction(async tx=>work(async(text,values=[])=>{const r=await tx.query(text,values);return {rows:r.rows,rowCount:r.affectedRows??r.rows.length};}))); }
 let root=repository(), db=root.forUser(owner);
 const storagePath=join(state,'files');await mkdir(storagePath);
 let failUpload=false, failDelete=false;
 const storage={
  async put(key,bytes){if(failUpload)throw new Error('storage offline');const file=join(storagePath,key);await mkdir(resolve(file,'..'),{recursive:true});await writeFile(file,bytes);},
  async get(key){try{const body=await readFile(join(storagePath,key));return {body,size:body.length};}catch(e){if(e.code==='ENOENT')return null;throw e;}},
  async delete(key){if(failDelete)throw new Error('storage offline');await rm(join(storagePath,key),{force:true});}
 };
 function handlers(){return createHandlers({database:user=>root.forUser(user||''),origin:()=>origin,storage:()=>storage,authenticate:async request=>{const id=request.headers.get('x-test-user');return id&&!request.headers.has('x-test-missing-email')?{userId:id,email:id+'@example.test'}:null;}});}
 async function req(path,{method='GET',body,user=owner,headers={}}={}){
  const h={...(user?{'x-test-user':user}:{}),...(method!=='GET'?{'Origin':origin,'X-Atlas-Request':'1'}:{}),...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{}),...headers};
  const request=new Request(origin+path,{method,headers:h,body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});
  return handlers()[method](request);
 }
 async function json(path,options,status=200){const r=await req(path,options);const body=await r.json();assert.equal(r.status,status,JSON.stringify(body));return body;}
 async function check(name,fn){await t.test(name,fn);count++;}
 const upload=(applicationId,filename='resume.pdf',bytes='%PDF-1.4\nAtlas harmless test fixture\n%%EOF')=>{const form=new FormData();form.set('application_id',applicationId);form.set('name','Resume v1');form.set('kind','Resume');form.set('status','Ready');form.set('notes','Tailored version');form.set('file',new File([bytes],filename,{type:'application/pdf'}));return form;};
 let c,a,i,n,d,otherC,otherA;
 try{
 await check('Health endpoint and security cache headers',async()=>{const r=await req('/api/health',{user:null});assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');});
 await check('Anonymous reads and writes require authentication',async()=>{await json('/api/workspace',{user:null},401);await json('/api/companies',{method:'POST',body:companyInput,user:null},401);});
 await check('Missing email also fails closed',async()=>{await json('/api/workspace',{headers:{'x-test-missing-email':'1'}},401);});
 await check('New account starts with an empty persisted workspace',async()=>{const s=await json('/api/workspace');assert.deepEqual(Object.keys(s).sort(),['applications','companies','documents','history','interviews','notes']);for(const rows of Object.values(s))assert.equal(rows.length,0);});
 await check('Cross-origin and missing CSRF headers are rejected',async()=>{await json('/api/companies',{method:'POST',body:companyInput,headers:{Origin:'https://evil.example'}},403);await json('/api/companies',{method:'POST',body:companyInput,headers:{'X-Atlas-Request':''}},403);await json('/api/companies',{method:'POST',body:companyInput,headers:{Origin:''}},403);});
 await check('Required fields, unsafe URLs, and unknown owner fields are rejected',async()=>{let r=await json('/api/companies',{method:'POST',body:{...companyInput,name:' '}},422);assert.ok(r.fields.name);await json('/api/companies',{method:'POST',body:{...companyInput,website:'javascript:alert(1)'}},422);await json('/api/companies',{method:'POST',body:{...companyInput,user_id:other}},422);});
 await check('JSON body size and content type are bounded',async()=>{await json('/api/companies',{method:'POST',body:{name:'X'.repeat(33000)}},413);await json('/api/companies',{method:'POST',body:companyInput,headers:{'Content-Type':'text/plain'}},415);});
 await check('Company create and read return a private clean record',async()=>{c=await json('/api/companies',{method:'POST',body:companyInput},201);assert.equal(c.name,companyInput.name);assert.equal(c.version,1);assert.ok(!('user_id'in c));assert.deepEqual(await json('/api/companies/'+c.id),c);});
 await check('Duplicate company names are rejected case-insensitively',async()=>{await json('/api/companies',{method:'POST',body:{...companyInput,name:companyInput.name.toUpperCase()}},409);});
 await check('Company edit increments its concurrency version',async()=>{c=await json('/api/companies/'+c.id,{method:'PATCH',body:{...companyInput,location:'Remote',version:c.version}});assert.equal(c.version,2);assert.equal(c.location,'Remote');});
 await check('Application creation and initial history are atomic',async()=>{a=await json('/api/applications',{method:'POST',body:applicationInput(c.id)},201);assert.equal(a.stage,'Wishlist');const s=await json('/api/workspace');assert.equal(s.applications.length,1);assert.equal(s.history.length,1);assert.equal(s.history[0].to_stage,'Wishlist');assert.equal(s.history[0].from_stage,null);});
 await check('Application validation rejects impossible dates and stages',async()=>{await json('/api/applications',{method:'POST',body:{...applicationInput(c.id),deadline:'2026-02-30'}},422);await json('/api/applications',{method:'POST',body:{...applicationInput(c.id),stage:'Hacked'}},422);});
 await check('Moving to Applied sets submission date and records history',async()=>{a=await json('/api/applications/'+a.id,{method:'PATCH',body:{...editable(a,aKeys),stage:'Applied',version:a.version}});assert.match(a.applied_on,/^\d{4}-\d{2}-\d{2}$/);const s=await json('/api/workspace');assert.ok(s.history.some(h=>h.from_stage==='Wishlist'&&h.to_stage==='Applied'));});
 await check('Concurrent stage changes allow exactly one winner and one event',async()=>{const before=(await json('/api/workspace')).history.length;const result=await Promise.all(['Screening','Interview'].map(stage=>req('/api/applications/'+a.id,{method:'PATCH',body:{...editable(a,aKeys),stage,version:a.version}})));assert.deepEqual(result.map(r=>r.status).sort(),[200,409]);a=await json('/api/applications/'+a.id);assert.equal((await json('/api/workspace')).history.length,before+1);});
 await check('Stale edits do not overwrite newer work',async()=>{const original=a.next_step;await json('/api/applications/'+a.id,{method:'PATCH',body:{...editable(a,aKeys),next_step:'Stale text',version:1}},409);assert.equal((await json('/api/applications/'+a.id)).next_step,original);});
 await check('Interview schedules normalize time zones to UTC',async()=>{i=await json('/api/interviews',{method:'POST',body:interviewInput(a.id)},201);assert.equal(i.starts_at,'2026-11-12T07:00:00.000Z');});
 await check('Interview can be rescheduled and marked completed',async()=>{i=await json('/api/interviews/'+i.id,{method:'PATCH',body:{...editable(i,iKeys),starts_at:'2026-11-13T09:30:00Z',status:'Completed',version:i.version}});assert.equal(i.status,'Completed');assert.equal(i.starts_at,'2026-11-13T09:30:00.000Z');});
 await check('Invalid interview duration and timestamp are rejected',async()=>{await json('/api/interviews',{method:'POST',body:{...interviewInput(a.id),duration_minutes:0}},422);await json('/api/interviews',{method:'POST',body:{...interviewInput(a.id),starts_at:'not-a-date'}},422);});
 await check('Notes save literal text and can be edited',async()=>{n=await json('/api/notes',{method:'POST',body:{application_id:a.id,body:'Research <script>alert(1)</script> remains plain text.'}},201);assert.match(n.body,/<script>/);n=await json('/api/notes/'+n.id,{method:'PATCH',body:{application_id:a.id,body:'Prepare a university project example.',version:n.version}});assert.equal(n.version,2);});
 await check('Blank and oversized notes are rejected',async()=>{await json('/api/notes',{method:'POST',body:{application_id:a.id,body:' '}},422);await json('/api/notes',{method:'POST',body:{application_id:a.id,body:'x'.repeat(4001)}},422);});
 await check('Document upload stores bytes privately with metadata',async()=>{d=await json('/api/documents',{method:'POST',body:upload(a.id)},201);assert.equal(d.content_type,'application/pdf');assert.equal(d.application_id,a.id);assert.ok(!('object_key'in d));assert.ok(!('user_id'in d));const r=await req('/api/documents/'+d.id+'/download');assert.equal(r.status,200);assert.match(r.headers.get('content-disposition'),/^attachment;/);assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(await r.text(),'%PDF-1.4\nAtlas harmless test fixture\n%%EOF');});
 await check('File extension, signature, empty file and size are validated',async()=>{await json('/api/documents',{method:'POST',body:upload(a.id,'evil.html','<html>')},422);await json('/api/documents',{method:'POST',body:upload(a.id,'fake.pdf','not-pdf')},422);await json('/api/documents',{method:'POST',body:upload(a.id,'empty.pdf','')},422);await json('/api/documents',{method:'POST',body:upload(a.id,'huge.pdf','%PDF-'+ 'x'.repeat(4*1024*1024))},413);});
 await check('Document status, title and application link are editable',async()=>{d=await json('/api/documents/'+d.id,{method:'PATCH',body:{...editable(d,dKeys),status:'Submitted',name:'Tailored resume',version:d.version}});assert.equal(d.status,'Submitted');assert.equal(d.version,2);});
 await check('Second identity creates its own separate workspace',async()=>{otherC=await json('/api/companies',{method:'POST',body:companyInput,user:other},201);otherA=await json('/api/applications',{method:'POST',body:applicationInput(otherC.id),user:other},201);const s=await json('/api/workspace',{user:other});assert.equal(s.applications.length,1);assert.equal(s.applications[0].id,otherA.id);assert.equal(s.notes.length,0);assert.equal(s.documents.length,0);});
 await check('Every cross-user record read and document download is denied',async()=>{for(const[table,row]of[['companies',c],['applications',a],['interviews',i],['notes',n],['documents',d]])await json(`/api/${table}/${row.id}`,{user:other},404);await json('/api/documents/'+d.id+'/download',{user:other},404);});
 await check('Cross-user edits and deletes are denied',async()=>{await json('/api/applications/'+a.id,{method:'PATCH',body:{...editable(a,aKeys),role:'Intrusion',version:a.version},user:other},404);await json(`/api/documents/${d.id}?version=${d.version}`,{method:'DELETE',user:other},404);});
 await check('Cross-user company and application links are denied',async()=>{await json('/api/applications',{method:'POST',body:applicationInput(c.id),user:other},404);await json('/api/interviews',{method:'POST',body:interviewInput(a.id),user:other},404);await json('/api/notes',{method:'POST',body:{application_id:a.id,body:'Intrusion'},user:other},404);await json('/api/documents',{method:'POST',body:upload(a.id),user:other},404);});
 await check('Composite foreign keys independently enforce ownership',async()=>{await assert.rejects(db.prepare('UPDATE applications SET company_id=? WHERE id=?').bind(otherC.id,a.id).run(),/foreign key/i);assert.equal((await json('/api/applications/'+a.id)).company_id,c.id);});
 await check('A failed SQL batch rolls back earlier writes',async()=>{await assert.rejects(db.batch([db.prepare('UPDATE applications SET next_step=? WHERE id=?').bind('Must be rolled back',a.id),db.prepare('UPDATE applications SET company_id=? WHERE id=?').bind(otherC.id,a.id)]),/foreign key/i);assert.equal((await json('/api/applications/'+a.id)).next_step,a.next_step);});
 await check('Company deletion is blocked while applications exist',async()=>{await json(`/api/companies/${c.id}?version=${c.version}`,{method:'DELETE'},409);});
 await check('Application deletion is blocked until files are unlinked',async()=>{await json(`/api/applications/${a.id}?version=${a.version}`,{method:'DELETE'},409);});
 await check('Private data and file bytes survive a PostgreSQL restart',async()=>{await pg.close();pg=new PGlite(join(state,'postgres'));root=repository();db=root.forUser(owner);const s=await json('/api/workspace');assert.equal(s.applications[0].id,a.id);assert.equal(s.notes[0].body,n.body);assert.equal(s.documents[0].id,d.id);assert.equal((await req('/api/documents/'+d.id+'/download')).status,200);});
 await check('Analytics handles empty data and records response history',async()=>{const empty=analytics(EMPTY);assert.equal(empty.responseRate,0);assert.equal(empty.offerRate,0);const result=analytics(await json('/api/workspace'));assert.equal(result.total,1);assert.equal(result.submitted,1);assert.equal(result.responseRate,100);assert.equal(result.offers,0);});
 await check('SQL-like company names are treated as data',async()=>{const x=await json('/api/companies',{method:'POST',body:{...companyInput,name:"' OR 1=1 --"}},201);assert.equal(x.name,"' OR 1=1 --");assert.ok((await json('/api/workspace')).applications.some(x=>x.id===a.id));await json(`/api/companies/${x.id}?version=1`,{method:'DELETE'});});
 await check('Pending document deletion blocks edits and can be retried',async()=>{await db.prepare('UPDATE documents SET deleting=1 WHERE id=?').bind(d.id).run();await json('/api/documents/'+d.id,{method:'PATCH',body:{...editable(d,dKeys),name:'Unsafe edit',version:d.version}},409);await json('/api/documents/'+d.id+'/download',{},409);await json(`/api/documents/${d.id}?version=${d.version}`,{method:'DELETE'});await json('/api/documents/'+d.id,{},404);await assert.rejects(readFile(join(storagePath,owner,'missing')));});
 await check('Individual note and interview deletion removes their records',async()=>{await json(`/api/notes/${n.id}?version=${n.version}`,{method:'DELETE'});await json(`/api/interviews/${i.id}?version=${i.version}`,{method:'DELETE'});await json('/api/notes/'+n.id,{},404);await json('/api/interviews/'+i.id,{},404);});
 await check('Application deletion cascades notes, interviews and history',async()=>{await json('/api/notes',{method:'POST',body:{application_id:a.id,body:'Temporary'}},201);await json('/api/interviews',{method:'POST',body:interviewInput(a.id)},201);await json(`/api/applications/${a.id}?version=${a.version}`,{method:'DELETE'});const s=await json('/api/workspace');for(const key of ['applications','notes','interviews','history'])assert.equal(s[key].length,0,key);await json(`/api/companies/${c.id}?version=${c.version}`,{method:'DELETE'});});
 await check('Other student remains unaffected by deletion',async()=>{const s=await json('/api/workspace',{user:other});assert.equal(s.applications[0].id,otherA.id);assert.equal(s.companies[0].id,otherC.id);});
 await check('Forged ChatGPT identity headers grant no access',async()=>{await json('/api/workspace',{user:null,headers:{'oai-authenticated-user-id':owner,'oai-authenticated-user-email':'owner@example.test'}},401);});
 await check('Row-level security restricts even unfiltered SQL',async()=>{const rows=await root.forUser(other).prepare('SELECT * FROM applications').run();assert.equal(rows.results.length,1);assert.equal(rows.results[0].id,otherA.id);const empty=await root.forUser('').prepare('SELECT * FROM applications').run();assert.equal(empty.results.length,0);});
 await check('RLS blocks inserting a different owner directly',async()=>{await assert.rejects(root.forUser(owner).prepare('INSERT INTO notes (id,user_id,application_id,body,created_at,updated_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),other,otherA.id,'forbidden','2026-01-01','2026-01-01').run(),/row-level security/i);});
 await check('Upload failure does not create metadata',async()=>{failUpload=true;await json('/api/documents',{method:'POST',body:upload('')},503);failUpload=false;assert.equal((await json('/api/workspace')).documents.length,0);});
 await check('Storage deletion failure keeps retryable metadata',async()=>{const doc=await json('/api/documents',{method:'POST',body:upload('')},201);const row=await db.prepare('SELECT object_key FROM documents WHERE id=?').bind(doc.id).first();failDelete=true;await json(`/api/documents/${doc.id}?version=1`,{method:'DELETE'},503);failDelete=false;await json(`/api/documents/${doc.id}?version=1`,{method:'DELETE'});await assert.rejects(readFile(join(storagePath,row.object_key)));});
 await check('Rate limiting blocks excessive write attempts',async()=>{await root.forUser(rateUser).prepare('INSERT INTO rate_limits (key,count,reset_at) VALUES (?,90,?) ON CONFLICT(key) DO UPDATE SET count=90,reset_at=excluded.reset_at').bind(rateUser,Date.now()+60000).run();await json('/api/companies',{method:'POST',body:companyInput,user:rateUser},429);});
 await check('Workspace quota blocks creation at the configured limit',async()=>{const now=new Date().toISOString();await root.forUser(quotaUser).batch(Array.from({length:300},(_,i)=>root.forUser(quotaUser).prepare('INSERT INTO companies (id,user_id,name,name_key,created_at,updated_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),quotaUser,String(i),String(i),now,now)));await json('/api/companies',{method:'POST',body:companyInput,user:quotaUser},409);});
 console.log(`\nExecuted ${count} major workflow and security checks against PostgreSQL and disk-backed files.\n`);
 }finally{await pg.close();await rm(state,{recursive:true,force:true});}
});
