'use client';
import { useState, type FormEvent } from 'react';
import { Loader2, UploadCloud } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { companySchema, applicationSchema, interviewSchema, noteSchema, documentSchema, STAGES, WORK_MODES, DOC_KINDS, DOC_STATUSES, INTERVIEW_STATUSES, type Snapshot } from '@/lib/atlas/contracts';
export type Kind = 'companies' | 'applications' | 'interviews' | 'notes' | 'documents';
export type EditorSpec = { kind: Kind; id?: string; defaults?: Record<string, unknown> };
export type ApiFailure = Error & { fields?: Record<string, string[]>; status?: number };
const schemas = { companies: companySchema, applications: applicationSchema, interviews: interviewSchema, notes: noteSchema, documents: documentSchema };
const singular = { companies: 'company', applications: 'application', interviews: 'interview', notes: 'note', documents: 'document' };
const defaults: Record<Kind, Record<string, unknown>> = { companies: { name: '', industry: '', location: '', website: '', contact_email: '', notes: '' }, applications: { company_id: '', role: '', stage: 'Wishlist', location: '', work_mode: 'Hybrid', job_url: '', applied_on: '', deadline: '', priority: 'Normal', compensation: '', next_step: '' }, interviews: { application_id: '', title: '', starts_at: '', duration_minutes: 30, format: 'Video call', location: '', meeting_url: '', interviewer: '', status: 'Scheduled', notes: '' }, notes: { application_id: '', body: '' }, documents: { application_id: '', name: '', kind: 'Resume', status: 'Draft', notes: '' } };
export function Choice({ label, value, onChange, options, id, disabled = false }: { label: string; value: string; onChange: (v: string) => void; options: readonly (string | { value: string; label: string })[]; id?: string; disabled?: boolean }) {
  return <Select value={value || undefined} onValueChange={onChange} disabled={disabled}><SelectTrigger id={id} aria-label={label} className="choice"><SelectValue placeholder={`Choose ${label.toLowerCase()}`} /></SelectTrigger><SelectContent position="popper">{options.map(o => { const option = typeof o === 'string' ? { value: o, label: o } : o; return <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>; })}</SelectContent></Select>;
}
export default function Editor({ spec, data, onClose, onSave }: { spec: EditorSpec; data: Snapshot; onClose: () => void; onSave: (kind: Kind, payload: Record<string, unknown> | FormData, id?: string) => Promise<void> }) {
  const existing = spec.id ? (data[spec.kind] as unknown as Record<string, unknown>[]).find(x => x.id === spec.id) : undefined;
  const initial = { ...defaults[spec.kind], ...existing, ...spec.defaults };
  if (spec.kind === 'interviews' && initial.starts_at) { const d = new Date(String(initial.starts_at)); initial.starts_at = new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
  const [values, setValues] = useState<Record<string, unknown>>(initial); const [errors, setErrors] = useState<Record<string, string[]>>({}); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [file, setFile] = useState<File | null>(null);
  const set = (key: string, value: unknown) => { setValues(v => ({ ...v, [key]: value })); setErrors(e => ({ ...e, [key]: [] })); };
  const field = (key: string, label: string, options?: { type?: string; choices?: readonly (string | { value: string; label: string })[]; area?: boolean; required?: boolean; placeholder?: string; full?: boolean; hint?: string }) => { const o = options || {}; const inputId = `editor-${spec.kind}-${key}`; return <div className={`field ${o.full ? 'full' : ''}`} key={key}><Label htmlFor={inputId}>{label}{o.required && <span className="required"> *</span>}</Label>{o.choices ? <Choice label={label} id={inputId} value={String(values[key] || '')} onChange={v => set(key, v)} options={o.choices} /> : o.area ? <Textarea id={inputId} value={String(values[key] ?? '')} onChange={e => set(key, e.target.value)} rows={4} maxLength={key === 'body' ? 4000 : 3000} placeholder={o.placeholder} aria-invalid={!!errors[key]?.length} aria-describedby={errors[key]?.length ? `${inputId}-error` : undefined} /> : <Input id={inputId} type={o.type || 'text'} value={String(values[key] ?? '')} onChange={e => set(key, o.type === 'number' ? Number(e.target.value) : e.target.value)} placeholder={o.placeholder} autoComplete="off" aria-invalid={!!errors[key]?.length} aria-describedby={errors[key]?.length ? `${inputId}-error` : undefined} />} {o.hint && <small>{o.hint}</small>}{errors[key]?.length > 0 && <p className="field-error" id={`${inputId}-error`}>{errors[key][0]}</p>}</div>; };
  const companyOptions = data.companies.map(c => ({ value: c.id, label: c.name })); const applicationOptions = data.applications.map(a => ({ value: a.id, label: `${data.companies.find(c => c.id === a.company_id)?.name} · ${a.role}` }));
  async function submit(e: FormEvent) {    
e.preventDefault(); if (busy) return; setError(''); const input: Record<string, unknown> = {}; for (const key of Object.keys(defaults[spec.kind])) input[key] = values[key];
    if (spec.kind === 'interviews') { const d = new Date(String(input.starts_at)); if (!isNaN(d.getTime())) input.starts_at = d.toISOString(); }
    const parsed = schemas[spec.kind].safeParse(input); if (!parsed.success) { setErrors(parsed.error.flatten().fieldErrors as Record<string, string[]>); setError('Please check the fields below.'); return; }
    if (spec.kind === 'documents' && !spec.id && !file) { setError('Choose a PDF, DOCX, or TXT file to upload.'); return; }
    setBusy(true); try {      
let payload: Record<string, unknown> | FormData = { ...parsed.data }; if (spec.id) payload.version = values.version;
      if (spec.kind === 'documents' && !spec.id) { const fd = new FormData(); for (const [k, v] of Object.entries(payload)) fd.set(k, String(v)); fd.set('file', file!); payload = fd; }
      await onSave(spec.kind, payload, spec.id); onClose();
    } catch (e) { const err = e as ApiFailure; setError(err.message); if (err.fields) setErrors(err.fields); } finally { setBusy(false); }  
}
  return <Dialog open onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className="editor-dialog" onPointerDownOutside={e => e.preventDefault()}><DialogHeader><DialogTitle>{spec.id ? 'Edit' : spec.kind === 'documents' ? 'Upload' : 'Add'} {singular[spec.kind]}</DialogTitle><DialogDescription>{spec.kind === 'applications' ? 'Keep the opportunity and your next step together.' : spec.kind === 'interviews' ? 'Times are entered in your device’s local time zone.' : spec.kind === 'documents' ? 'PDF, DOCX, or TXT · Up to 4 MB per file.' : spec.kind === 'notes' ? 'Capture details you’ll want to remember.' : 'Save the details that matter for your search.'}</DialogDescription></DialogHeader>
    <form onSubmit={submit} noValidate><div className="form-scroll">{error && <div className="error-banner" role="alert">{error}</div>}<div className="form-grid">
      {spec.kind === 'companies' && <>{field('name', 'Company name', { required: true, full: true, placeholder: 'e.g. Northstar' })}{field('industry', 'Industry', { placeholder: 'e.g. Software' })}{field('location', 'Location', { placeholder: 'e.g. Bangkok, Thailand' })}{field('website', 'Website', { type: 'url', placeholder: 'https://...', full: true })}{field('contact_email', 'Contact email', { type: 'email', full: true })}{field('notes', 'Company notes', { area: true, full: true })}</>}
      {spec.kind === 'applications' && <>{field('company_id', 'Company', { choices: companyOptions, required: true, full: true })}{field('role', 'Internship role', { required: true, full: true, placeholder: 'e.g. Product Management Intern' })}{field('stage', 'Stage', { choices: STAGES })}{field('priority', 'Priority', { choices: ['Normal', 'High', 'Low'] })}{field('location', 'Location', { placeholder: 'e.g. Bangkok' })}{field('work_mode', 'Work arrangement', { choices: WORK_MODES })}{field('applied_on', 'Date applied', { type: 'date' })}{field('deadline', 'Application deadline', { type: 'date' })}{field('job_url', 'Job posting', { type: 'url', placeholder: 'https://...', full: true })}{field('compensation', 'Compensation', { full: true, placeholder: 'e.g. ฿15,000 / month, or not listed' })}{field('next_step', 'Next step', { area: true, full: true, placeholder: 'What’s the next thing you need to do?' })}</>}
      {spec.kind === 'interviews' && <>{field('application_id', 'Application', { choices: applicationOptions, required: true, full: true })}{field('title', 'Interview title', { required: true, full: true, placeholder: 'e.g. Product case interview' })}{field('starts_at', 'Date and time', { type: 'datetime-local', required: true })}{field('duration_minutes', 'Duration (minutes)', { type: 'number', required: true })}{field('format', 'Format', { choices: ['Video call', 'Phone', 'In person'] })}{field('status', 'Status', { choices: INTERVIEW_STATUSES })}{field('interviewer', 'Interviewer', { full: true })}{field('meeting_url', 'Meeting link', { type: 'url', full: true, placeholder: 'https://...' })}{field('location', 'Location or phone details', { full: true })}{field('notes', 'Preparation notes', { area: true, full: true })}</>}
      {spec.kind === 'notes' && <>{field('application_id', 'Application', { choices: applicationOptions, required: true, full: true })}{field('body', 'Note', { area: true, required: true, full: true, placeholder: 'Recruiter feedback, your research, or questions to ask…' })}</>}
      {spec.kind === 'documents' && <>{!spec.id && <div className="field full"><label className="upload-area" htmlFor="document-file"><UploadCloud /><strong>{file ? file.name : 'Choose a document'}</strong><span>{file ? `${(file.size / 1024).toFixed(0)} KB` : 'PDF, DOCX, TXT · 4 MB maximum'}</span><input id="document-file" type="file" accept=".pdf,.docx,.txt" onChange={e => { const f = e.target.files?.[0] || null; if (f && f.size > 4 * 1024 * 1024) { setError('Files must be 4 MB or smaller.'); return; } setFile(f); if (f && !values.name) set('name', f.name.replace(/\.[^.]+$/, '')); setError(''); }} /></label></div>}{field('name', 'Document name', { full: true, required: true })}{field('kind', 'Document type', { choices: DOC_KINDS })}{field('status', 'Document status', { choices: DOC_STATUSES })}<div className="field full"><Label htmlFor="document-app">Application (optional)</Label><Choice label="Application" id="document-app" value={String(values.application_id || 'unlinked')} onChange={v => set('application_id', v === 'unlinked' ? '' : v)} options={[{ value: 'unlinked', label: 'General document' }, ...applicationOptions]} />{errors.application_id?.length > 0 && <p className="field-error">{errors.application_id[0]}</p>}</div>{field('notes', 'Document notes', { area: true, full: true })}</>}
    </div></div><footer className="form-footer"><button type="button" className="btn secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="btn primary" type="submit" disabled={busy}>{busy && <Loader2 className="spin" />}{busy ? 'Saving…' : spec.kind === 'documents' && !spec.id ? 'Upload document' : spec.id ? 'Save changes' : `Add ${singular[spec.kind]}`}</button></footer></form>
  </DialogContent></Dialog>;
}
