import { type Snapshot, type Stage } from './contracts';
export function sampleWorkspace(): Snapshot {
  const now = new Date(); const at = (d: number) => new Date(now.getTime() + d * 86400000).toISOString(); const uid = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
  const companyNames = [['Northstar', 'Software', 'Bangkok'], ['Forma Studio', 'Design & technology', 'Remote'], ['Meridian', 'Financial technology', 'Singapore'], ['Orbit Labs', 'Technology', 'Bangkok'], ['Evergreen', 'Sustainability', 'Remote'], ['Lumen', 'Consumer technology', 'Bangkok']];
  const companies = companyNames.map(([name, industry, location], i) => ({ id: uid(i + 1), name, industry, location, website: '', contact_email: '', notes: '', version: 1, created_at: at(-30), updated_at: at(-i) }));
  const stages: Stage[] = ['Interview', 'Screening', 'Applied', 'Offer', 'Wishlist', 'Applied', 'Rejected', 'Interview'];
  const roles = ['Product Management Intern', 'UX Research Intern', 'Business Analyst Intern', 'Frontend Engineering Intern', 'Operations Intern', 'Data Analyst Intern', 'Marketing Intern', 'Digital Innovation Intern'];
  const applications = stages.map((stage, i) => ({ id: uid(100 + i), company_id: companies[i % 6].id, role: roles[i], stage, location: companies[i % 6].location, work_mode: (i % 3 === 0 ? 'Hybrid' : i % 3 === 1 ? 'Remote' : 'On-site') as 'Hybrid' | 'Remote' | 'On-site', job_url: '', applied_on: stage === 'Wishlist' ? '' : at(-i * 9 - 4).slice(0, 10), deadline: at(4 + i).slice(0, 10), priority: (i === 0 ? 'High' : 'Normal') as 'High' | 'Normal', compensation: '', next_step: i === 0 ? 'Prepare two examples of a product decision.' : i === 3 ? 'Review the offer and prepare your questions.' : '', version: 1, created_at: at(-i * 9 - 7), updated_at: at(-i) }));
  const interviews = [{ id: uid(200), application_id: applications[0].id, title: 'Product case interview', starts_at: at(2), duration_minutes: 45, format: 'Video call' as const, location: '', meeting_url: '', interviewer: 'Hiring team', status: 'Scheduled' as const, notes: 'Prepare a short walkthrough of a product you use.', version: 1, created_at: at(-1), updated_at: at(-1) }, { id: uid(201), application_id: applications[7].id, title: 'Team introduction', starts_at: at(4), duration_minutes: 30, format: 'In person' as const, location: 'Bangkok office', meeting_url: '', interviewer: '', status: 'Scheduled' as const, notes: '', version: 1, created_at: at(-2), updated_at: at(-2) }];
  return { companies, applications, interviews, notes: [{ id: uid(300), application_id: applications[0].id, body: 'The role combines product research and business analysis. Prepare one example from a university project and one from a personal project.', version: 1, created_at: at(-1), updated_at: at(-1) }], documents: [], history: applications.map((a, i) => ({ id: uid(400 + i), application_id: a.id, from_stage: null, to_stage: a.stage, created_at: a.updated_at })) };
}
